#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4 encoding=utf-8

from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to, direct_to_template
from ..models import get_geography, ProductStock, ProductReport

urlpatterns = patterns('',
    url(r'^no_ie_allowed/?$', 'logistics.views.no_ie_allowed', 
        name="no_ie_allowed"),
    url(r'^(?P<facility_code>[\w-]+)/input_stock$',
        'logistics.views.input_stock',
        name="input_stock"),
    # ok, so this isn't the most generic, but we don't yet know what the final dashboard will look like
    # so we'll use this as a placeholder until we do
    url(r'^dashboard/?$',
        'logistics.views.dashboard',
        name="logistics_dashboard"),
    url(r'^aggregate/?$',
        'logistics.views.aggregate',
        name="aggregate"),
    url(r'^facilities_by_products/?$',
        'logistics.views.facilities_by_products',
        name="facilities_by_products"),
    url(r'^(?P<facility_code>[\w-]+)/stockonhand/?$',
        'logistics.views.stockonhand_facility',
        name="stockonhand_facility"),
    url(r'^by_product/?$',
        'logistics.views.facilities_by_product',
        name="by_product"),
    url(r'^reporting$',
        'logistics.views.reporting',
        name="reporting"),
    url(r'^(?P<facility_code>\w+)/stockonhand/export/xls$', 
        'logistics.views.export_stockonhand',  
        name="export_stock"),
    url(r'^navigate$', 
        'logistics.views.navigate',  
        name="navigate"),
    url(r'^messages_by_carrier$',
        'logistics.views.messages_by_carrier',
        name="messages_by_carrier"),
    url(r'^district_dashboard', 
        'logistics.views.district_dashboard',  
        name="district_dashboard"),
    url(r'^email-summary$',
        'logistics.views.summary',
        name="email-summary"),
    url(r'^excel-export$',
        'logistics.views.excel_export',
        name="excel-export"),
    url(r'^ajax/contact_dropdown$',
        'logistics.views.ajax_contact_dropdown',
        name="ajax_contact_dropdown"),
    url(r'^export_periodic_stock',
        'logistics.views.export_periodic_stock',
        name="export_periodic_stock"), 
    url(r'^export_reporting',
        'logistics.views.export_reporting',
        name="export_reporting")
)
